name: yollet_system
description: Yollet System Package
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # REST API Related Dependencies
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.1
  json_annotation: ^4.1.0

  # REDUX Related Dependencies
  redux: ^5.0.0
  flutter_redux: ^0.8.2

  # Routing Related Dependencies
  auto_route: ^3.2.4

  # Additional Related Dependencies
  intl: ^0.17.0
  intl_utils: ^2.6.1
  get: ^4.6.1
  heroicons: ^0.3.0
  dropdown_button2: ^1.0.6
  hovering: ^1.0.4
  syncfusion_flutter_datagrid: ^19.4.43
  flutter_screenutil: ^5.0.0+2
  image_picker: ^0.8.4+11
  responsive_framework: ^0.1.7
  mix: ^0.0.6

  # Database Related Dependencies
  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

